CREATE TABLE [dbo].[RegisteredUsers]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Email] VARCHAR(50) NOT NULL UNIQUE,
	[Password] NVARCHAR(100) NOT NULL,
	CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([Id] ASC)
)
